CREATE TABLE managers (
    ID_MNG INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    BIRTH_DATE TEXT
);

CREATE TABLE employees (
  ID_EMPLOYEE INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT DEFAULT NULL,
  BIRTH_DATE DATE DEFAULT NULL,
  POSITION TEXT DEFAULT NULL
);

CREATE TABLE clients (
  ID_C INTEGER PRIMARY KEY AUTOINCREMENT,
  CODE_C INTEGER NOT NULL,
  NAME TEXT DEFAULT NULL,
  BIRTH_DATE DATE DEFAULT NULL,
  TELEPHONE TEXT DEFAULT NULL,
  EMAIL_USER TEXT DEFAULT NULL
);

CREATE TABLE files (
  ID_FILE INTEGER PRIMARY KEY AUTOINCREMENT,
  TITLE TEXT DEFAULT NULL,
  CONTENT TEXT,
  REGISTRATION_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  REVIEW INTEGER DEFAULT 0,
  REVIEWER INTEGER DEFAULT NULL,      
  ID_EMPLOYEE INTEGER DEFAULT NULL ,
  FOREIGN KEY (REVIEWER) REFERENCES managers(ID_MNG),
  FOREIGN KEY (ID_EMPLOYEE) REFERENCES employees(ID_EMPLOYEE)
);
CREATE TABLE CLIENT_STATUS (
  CODE_C INTEGER PRIMARY KEY,
  HAS_BAD_DEBT INTEGER DEFAULT 0,
  JOB_TITLE TEXT DEFAULT NULL,
  MONTHLY_INCOME INTEGER NOT NULL
);



ALTER TABLE files 
RENAME COLUMN REVIEWER TO ID_MNG;



