/*2.List all files reviewed by employee and manager.*/
SELECT F.TITLE, F.REGISTRATION_TIME, E.NAME AS EmployeeName, M.NAME AS ManagerName
FROM FILES F
LEFT JOIN EMPLOYEES E ON F.ID_EMPLOYEE = E.ID_EMPLOYEE
LEFT JOIN MANAGERS M ON F.ID_MNG = M.ID_MNG
WHERE F.REVIEW = 1
ORDER BY F.REGISTRATION_TIME DESC;