/*3.Find the customers with the highest and lowest income.*/

SELECT C.NAME, S.MONTHLY_INCOME
FROM CLIENT_STATUS S
JOIN CLIENTS C ON C.CODE_C = S.CODE_C
WHERE S.MONTHLY_INCOME = (
    SELECT MAX(MONTHLY_INCOME) FROM CLIENT_STATUS
)
OR S.MONTHLY_INCOME = (
    SELECT MIN(MONTHLY_INCOME) FROM CLIENT_STATUS
);