/*6.TRIGGER :Automatically update bad debt status when income < 1000*/

CREATE TRIGGER update_bad_debt
AFTER UPDATE OF MONTHLY_INCOME ON CLIENT_STATUS
FOR EACH ROW
WHEN NEW.MONTHLY_INCOME < 1000
BEGIN
  UPDATE CLIENT_STATUS
  SET HAS_BAD_DEBT = 1
  WHERE CODE_C = NEW.CODE_C;
END;