create database retail_banking_db;


/*
MANAGERS(ID_MNG, NAME)
REPOSTER(ID_REPOSTER, NAME , DATE , ORGANIZATION )
USER(ID_USER , ACCOUNT_NAME, PASSWORD , FACEBOOK_USER, EMAIL_USER )
POST(ID_POST , TITLE , CONTENT , IMAGE, VIEW, REVIEW, REVIEWER , POSTING_TIME )
SHARE(ID_SHARE, TIME_SHARE)
COMMENT(ID_COMMENT , TIME_COMMENT, CONTENT)
*/

CREATE TABLE managers (
	ID_MNG int auto_increment primary key,
    BIRTH_DATE date,
    NAME varchar(50)
);

CREATE TABLE employees (
  ID_EMPLOYEE int NOT NULL AUTO_INCREMENT,
  NAME varchar(100) DEFAULT NULL,
  BIRTH_DATE date DEFAULT NULL,
  POSITION varchar(100) DEFAULT NULL,
  PRIMARY KEY (ID_EMPLOYEE)
);

CREATE TABLE clients (
  ID_C int NOT NULL AUTO_INCREMENT,
  CODE_C INT NOT NULL,
  NAME varchar(100) DEFAULT NULL,
  BIRTH_DATE date DEFAULT NULL,
  TELEPHONE varchar(50) DEFAULT NULL,
  EMAIL_USER varchar(100) DEFAULT NULL,
  PRIMARY KEY (ID_C)
);

CREATE TABLE files (
  ID_FILE int NOT NULL AUTO_INCREMENT,
  TITLE varchar(100) DEFAULT NULL,
  CONTENT text,
  REGISTRATION_TIME datetime DEFAULT CURRENT_TIMESTAMP,
  REVIEW tinyint DEFAULT 0,
  REVIEWER int DEFAULT NULL,
  ID_EMPLOYEE int DEFAULT NULL,
  PRIMARY KEY (ID_FILE)
);

CREATE TABLE CLIENT_STATUS (
	CODE_C INT PRIMARY KEY,
    HAS_BAD_DEBT tinyint DEFAULT 0,
    JOB_TITLE varchar(100) DEFAULT NULL,
    MONTHLY_INCOME int NOT NULL,
);

